openapi: 3.0.4
info:
  title: Geoworktracker log models
  description: Log models for logging services of geoworktracker
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.0
paths: {}

components:
  schemas:
    CommonLogModel:
      title: Общая модель лога
      description: Общая модель лога для всех микросервисов системы
      type: object
      properties:
        messageTime:
          type: string
        logId:
          type: string
        source:
          type: string
        ticket:
          $ref: '#/components/schemas/GwtrLogModel'
#        comments:
#          $ref: '#/components/schemas/GwtrLogModel'
#        files:
#          $ref: '#/components/schemas/GwtrLogModel'
#        images:
#          $ref: '#/components/schemas/GwtrLogModel'
        errors:
          type: array
          items:
            $ref: '#/components/schemas/ErrorLogModel'

# переименовать в GwtrTicketLogModel
    GwtrLogModel:
      title: Модель лога для микросервиса Geoworktracker
      type: object
      properties:
        requestId:
          type: string
        operation:
          $ref: '#/components/schemas/GwtrLogOperation'
        requestTicket:
          $ref: '#/components/schemas/TicketLog'
        requestFilter:
          $ref: '#/components/schemas/TicketFilterLog'
        responseTicket:
          $ref: '#/components/schemas/TicketLog'
        responseTickets:
          type: array
          items:
            $ref: '#/components/schemas/TicketLog'

    GwtrLogOperation:
      type: string
      enum:
        - create
        - read
        - update
        - delete
        - search
        - init
        - finish

    ErrorLogModel:
      title: Модель лога для ошибки
      type: object
      properties:
        message:
          type: string
        field:
          type: string
        code:
          type: string
        level:
          type: string

    TicketLog:
      title: Модель лога для тикета
      type: object
      properties:
        id:
          type: string
        title:
          type: string
        description:
          type: string
        ticketType:
          type: string
        visibility:
          type: string
        ownerId:
          type: string
        siteId:
          type: string
        permissions:
          type: array
          uniqueItems: true
          items:
            type: string

    TicketFilterLog:
      title: Модель лога фильтра
      properties:
        searchString:
          type: string
        ownerId:
          type: string
        claimStatus:
          type: string

